apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.2.0-runtime-ubuntu22.04
    resources:
      limits:
        nvidia.com/gpu: 8
    command: ["sleep", "infinity"]
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-l4
